---
name: Checks

on: [push] #when this workflow should run

jobs:
  test-lint:     
    name: Test and Lint 
    runs-on: ubuntu-20.04 
    steps: #what are the steps that need to run mentioned here
      - name: Login to Docker Hub 
        uses: docker/login-action@v1  #action already in github for logging into docker
        with:
          username: ${{ secrets.DOCKERHUB_USER }} #variables which we have set in github
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2 #github action used for accessing code
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"